% From Yonghao Pua  <puayonghao@gmail.com>

\documentclass{article}
\usepackage{relsize,setspace} % used by latex(describe( ))
\usepackage{longtable}
\usepackage{pdfpages}
\usepackage{hyperref}
\usepackage{lscape} % for landscape mode tables
\usepackage{calc,epic,color} % used for latex(..., dotchart=TRUE)
\usepackage[superscript,nomove]{cite} % use if \cite is used and superscripts wanted
\usepackage{helvet}
\usepackage{moreverb}
\renewcommand{\familydefault}{\sfdefault}
\newcommand{\R}{{\normalfont\textsf{R}}{}}

\textwidth 6.75in % set dimensions before fancyhdr
\textheight 9.25in
\topmargin -.875in
\oddsidemargin -.125in
\evensidemargin -.125in
\usepackage{fancyhdr} % this and next line are for fancy headers/footers
\pagestyle{fancy}
\lhead{\textsc{}} %uncomment to remove left-sided headings
\setlength{\parindent}{0ex} % don't indent first line of paragraph
\setlength{\parskip}{2ex} % do skip 2 spaces between paragraphs

\title{\textsf{Example illustrating problems with latex.summaryM}}
\author{Pua Yong Hao\\\smaller\href{mailto:puayonghao@gmail.com}{puayonghao@gmail.com}} 
\date{\today}
\begin{document}
\maketitle

\section{Descriptive Stats}
<<echo=TRUE, results='hide'>>=
library(rms)
n <- 500; set.seed(88)
sex <- factor(sample(c("female","male"), n, TRUE))
age <- rnorm(n, 50, 10)
height <- rnorm(n, 1.7, 0.5)
type <- factor(sample(c('A', 'B'), n, TRUE))
dbase= data.frame(sex, age, height, type)
dbase.dd <- datadist(dbase)
options(datadist = "dbase.dd")
@

When I use the \texttt{summaryM} function, note that the table footers are shown as captions.
<<echo=FALSE, results='asis'>>=
latex(summaryM(age + height + type ~ sex , data=dbase, overall=TRUE, test=TRUE),
      size='small', where="ht",  
      long=TRUE, prmsd = TRUE,
      caption="Descriptive Statistics",
      msdsize='scriptsize', round = 2, digits=2, prtest='P', pdig =2, file='',
      label="table:summary")
@
\end{document}
